name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Updated to the latest version
        with:
          fetch-depth: 0
      
      - name: Add remote
        env:
          SENTIMENT: ${{ secrets.Sentiment }}  # Use uppercase for environment variables
        run: git remote add space https://irfan1002:${{ secrets.Sentiment }}@huggingface.co/spaces/irfan1002/TextSentimentAnalysis
      
      - name: Push to hub
        env:
          SENTIMENT: ${{ secrets.Sentiment }}  # Use uppercase for environment variables
        run: git push --force https://irfan1002:${{ secrets.Sentiment }}@huggingface.co/spaces/irfan1002/TextSentimentAnalysis main
